cloud:
  aws:
    credentials:
      access-key: AKIAXYKJVWNNJECAYO7U
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: myfood-images

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
